print (" >>> Ola , Bem vindo ao Burguer king ! <<<")
print (" >>> O pedido estara a Baixo ! <<< ")
print ("Triple bacon - 14 , 90 R$")
print ("Big king - 14 , 90 R$")
print ("Cheddar Duplo - 12 , 75 R$")
print ("Whopper - 20 , 90 R$")
print ("Chicken Duplo - 13 , 90 R$")
print (">>> Bebidas <<<")
print ("Pepsi - 6 , 90 R$")
print ("Coca cola - 8 , 90 R$")
print ("Fanta Uva - 8 , 90 R$")
print ("Fanta laranja - 8 , 90 R$")
f = str(input(" Mais alguma coisa ? ")) 
print (" Obrigado pela Preferencia ! ")
